# Loading all necessary packages

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import AgglomerativeClustering, KMeans
from scipy.cluster import hierarchy

# Part 1 - Import and preprocess
1. Read Excel file and set column 0 as index
2. Dropping empty lines
3. Keeping a copy of the raw data in `df_raw`
4. Normalizing data in `df`

In [24]:
# Read in Data using pandas
df_raw = pd.read_excel('Exercise3_data.xlsx', index_col=0)

# Dropping empty lines
df_raw = df_raw.drop(df_raw.index[0:3])
df = df_raw.copy()

# normalize by column
df = (df - df.min()) / (df.max() - df.min())

df

,Distance,Cost,LO,Water,GWP,FWET,FWEU,HT,PMPF,POFP,TA,TE
BD20 algae,1.0,0.661017,0.003428,0.02439,0.97166,0.324324,0.223653,0.253165,0.387805,0.534848,0.628959,0.649123
BD20 Camelina,1.0,0.559322,0.195373,0.117517,0.927126,0.201201,0.032787,0.063291,0.209756,0.386364,0.473605,0.54386
BD20 canola,1.0,0.610169,0.101971,0.064302,0.927126,0.201201,0.038642,0.063291,0.197561,0.356061,0.455505,0.596491
BD20 corn,1.0,0.525424,0.312768,0.137472,0.959514,0.231231,0.045667,0.075949,0.285366,0.522727,0.556561,0.508772
BD20 Jatropha,1.0,0.525424,0.093402,0.055432,0.94332,0.231231,0.038642,0.075949,0.236585,0.431818,0.505279,0.508772
...,...,...,...,...,...,...,...,...,...,...,...,...
RDII canola,0.923077,0.771186,0.520137,0.32816,0.032389,0.162162,0.067916,0.037975,0.043902,0.087879,0.033183,0.763158
RDII corn,0.923077,0.29661,0.841474,0.055432,0.165992,0.339339,0.096019,0.113924,0.421951,0.822727,0.461538,0.27193
RDII Jatropha,0.923077,0.288136,0.474722,0.280488,0.11336,0.327327,0.069087,0.088608,0.243902,0.477273,0.285068,0.263158
RDII palm,0.923077,0.491525,0.239075,1.0,0.0,0.144144,0.038642,0.012658,0.080488,0.190909,0.095023,0.473684
RDII soy,0.923077,0.669492,0.97515,0.386918,0.020243,0.138138,0.044496,0.037975,0.029268,0.072727,0.037707,0.657895

# Part 2 - Hierarchical clustering
1. test
2. test